#-----------------------------------------
# Site
#-----------------------------------------
repository: nszilard/nszilard.github.io
favicon:    images/favicon.ico
locale:     en

#-----------------------------------------
# Personal info
#-----------------------------------------
name:  Szil√°rd Attila Nagy
title: DevSecOps Engineer

#-----------------------------------------
# Social links
#-----------------------------------------
github_username:    nszilard
linkedin_username:  nagyszilard94
instagram_username: nszilard
facebook_username:  szilard.nagy.547
twitter_username:   TheSzilardNagy

#-----------------------------------------
# Sections
#-----------------------------------------
awards_title:     Awards
experience_title: Work Experience
more_content:     Enabled

#-----------------------------------------
# Footer
#-----------------------------------------
footer_show_references: false

#-----------------------------------------
# Build settings
#-----------------------------------------
remote_theme: sproogen/resume-theme
darkmode:     false
sass:
  sass_dir: _sass
  style: compressed


#-----------------------------------------
# Plugins
#-----------------------------------------
plugins:
 - jekyll-seo-tag

#-----------------------------------------
# Excludes
#-----------------------------------------
exclude : [
  "Gemfile",
  "Gemfile.lock"
]
